paths:
  /api/products:
    get:
      summary: Obtiene todos los productos de la DB.
      tags:
        - Products
      description: Devuelve una lista de todos los productos almacenados en la base de datos.
      responses:
        "200":
          description: Productos obtenidos exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        "404":
          description: Productos no encontrados.
        "500":
          description: Error interno del servidor.
    post:
      summary: Crea un nuevo producto.
      tags:
        - Products
      requestBody:
        description: Cuerpo de la solicitud para crear un nuevo producto.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProduct'
      responses:
        "200":
          description: Producto creado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewProduct'
        "400":
          description: Solicitud inválida.
        "500":
          description: Error interno del servidor.
  /api/products/{pid}:
    get:
      summary: Obtiene el producto según id.
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto que se desea encontrar/buscar.
          schema:
            type: string
            example: 66341e3bae100d582fa75341
      responses:
        "200":
          description: Producto obtenido exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "404":
          description: Producto no encontrado.
        "500":
          description: Error interno del servidor.
    delete:
      summary: Elimina un producto de la DB.
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto que se desea eliminar.
          schema:
            type: string
      requestBody:
        description: Cuerpo de solicitud para la eliminación de un producto.
        required: false  # El cuerpo puede no ser necesario para un DELETE, ajusta si es necesario
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteProduct'
      responses:
        "200":
          description: Producto eliminado exitosamente.
        "404":
          description: Producto no encontrado.
        "500":
          description: Error interno del servidor.
    put:
      summary: Actualiza un producto existente.
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto que se desea actualizar.
          schema:
            type: string  
            example: 66341e3bae100d582fa75341
      requestBody:
        description: Cuerpo de solicitud para la actualización de un producto.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductUpdated'
      responses:
        "200":
          description: Producto actualizado exitosamente.
        "404":
          description: Producto no encontrado.
        "500":
          description: Error interno del servidor.

components:
  schemas:
    NewProduct:
      type: object
      properties:
        newProduct:
          type: object
          properties:
            owner:
              type: string
              description: Email del owner
              example: dsadas@gmail.com
            title:
              type: string
              description: Título del producto
              example: SUPER MAN 311
            category:
              type: string
              description: Categoría del producto
              example: acción
            description:
              type: string
              description: Descripción del producto
              example: Hachiko (Batong) es un lindo perro pastor chino. Conoce a su dueño Chen Jingxiu entre la gran multitud y se convierte en miembro de la familia Chen. Con el paso del tiempo, la casa que alguna vez fue hermosa ya no está allí, pero Batong espera y espera, sabiendo que su destino está estrechamente ligado a su familia.
            price:
              type: number
              format: float
              description: Precio del producto
              example: 20000
            thumbnail:
              type: string
              description: Imagen del producto
              example: https://static.cinemarkhoyts.com.ar/Images/Posters/6a12441fc44c3621acf8a43b92861c8e.jpg?v=00002337
            stock:
              type: number
              description: Cantidad en stock
              example: 10
            status:
              type: boolean
              description: Disponibilidad del producto
              example: true
            _id:
              type: string
              description: ID del producto
              example: 66aba199cb388082ae23ea51
            code:
              type: number
              description: Código de identificación del producto
              example: 777
    CreateProduct:
      type: object
      properties:
        owner:
          type: string
          description: Email del owner
          example: mia@gmail.com
        title:
          type: string
          description: Título del producto
          example: GARFIELD FUERA DE CASA
        category:
          type: string
          description: Categoría del producto
          example: animación
        description:
          type: string
          description: Descripción del producto
          example: Garfield, el famoso gato amante de la lasaña que odia los lunes, está…
        price:
          type: number
          format: float
          description: Precio del producto
          example: 2000
        thumbnail:
          type: string
          description: Imagen del producto
          example: https://static.cinemarkhoyts.com.ar/Images/Posters/2bc9ca70c2febb6faf5…
        stock:
          type: number
          description: Cantidad en stock
          example: 5
        status:
          type: boolean
          description: Disponibilidad del producto
          example: true
    Product:
      type: object
      properties:
        owner:
          type: string
          description: Email del owner
          example: mia@gmail.com
        title:
          type: string
          description: Título del producto
          example: GARFIELD FUERA DE CASA
        category:
          type: string
          description: Categoría del producto
          example: animación
        description:
          type: string
          description: Descripción del producto
          example: Garfield, el famoso gato amante de la lasaña que odia los lunes, está…
        price:
          type: number
          format: float
          description: Precio del producto
          example: 2000
        thumbnail:
          type: string
          description: Imagen del producto
          example: https://static.cinemarkhoyts.com.ar/Images/Posters/2bc9ca70c2febb6faf5…
        stock:
          type: number
          description: Cantidad en stock
          example: 5
        status:
          type: boolean
          description: Disponibilidad del producto
          example: true
        _id:
          type: string
          description: ID del producto
          example: 66aba199cb388082ae23ea51
        code:
          type: number
          description: Código de identificación del producto
          example: 777
    DeleteProduct:
      type: object
      properties:
        email:
          type: string
          example: mia@gmail.com
    ProductUpdated:
      type: object
      properties:
        email:
          type: string
          description: Email del usuario
          example: mia@gmail.com
        price:
          type: number
          description: Monto actualizado
          example: 6000